### ISSUE TITLE
[textcase] When \NoCaseChange{} is used in \MakeUppercase{}, \o is left capitalized

### ISSUE THREAD

**Issue by GAndreikenas** [davidcarlisle/dpctex#35]
Hello,

I've got the following issue: the title of journal's article should be capitalized, text from `\thanks{}` inside the `\title{}` is `\NoCaseChange`ed, but `\o` is still capitalized. Here is MWE:
```
\documentclass{article}
\usepackage{textcase}

\makeatletter
\def\title#1{\gdef\@title{\MakeUppercase{#1}}}
\let\case@thanks\thanks
\def\thanks#1{\NoCaseChange{\case@thanks{#1}}}
\makeatother

\begin{document}
\title{My title\thanks{Thanks to Hedda Hassel M\o rch}}
\author{My Name}
\maketitle
\end{document}
```

Thanks,
Giedrius

**Comment by davidcarlisle** [comment]
With a current release `textcase` does nothing and if I delete it I get

![image](https://user-images.githubusercontent.com/1268738/193023613-54384a89-ce76-4908-be4e-6cf29e3feb0d.png)


from

```
\documentclass{article}


\makeatletter
\def\title#1{\gdef\@title{\MakeUppercase{#1}}}
\let\case@thanks\thanks
\def\thanks#1{\NoCaseChange{\case@thanks{#1}}}
\makeatother

\begin{document}
\title{My title\thanks{Thanks to Hedda Hassel M\o rch}}
\author{My Name}
\maketitle
\end{document}
```

In older LaTeX releases you would have needed to use `MakeTextUppercase` rather than `MakeUppercase` to have any effect or use the `[overload]` package option.

As textcase 2022/07/10 v1.03 does nothing at all in current Latex and the new MakeUppercase (which is generally Unicode-aware) seems to work here, I think I can close with no action?

**Comment by GAndreikenas** [comment]
Unfortunately, with TL2019 `MakeTextUppercase` does not solve the problem - `\o` stays capitalized.

**Comment by davidcarlisle** [comment]
I may be able to suggest something but not really _here_ the package here does nothing now (as `\NoCaseChange` is built in to latex now, and your problem is fixed there) and any change I make here or on ctan would only go to texlive 2022 and later.  

if you use OT1 (as in your example) `\o` is 

`\DeclareTextSymbol{\o}{OT1}{28}` so you could use `\symbol{28}` 

in T1 encoding it is

`\DeclareTextSymbol{\o}{T1}{248}` so you could use `\symbol{248}`

**Comment by GAndreikenas** [comment]
Thanks for the help.
