### ISSUE TITLE
Importing colortbl changes horizontal spacing

### ISSUE THREAD

**Issue by jovyntls** [davidcarlisle/dpctex#48]
`\usepackage{colortbl}` changes the spacing of tables even when no other commands from the package are used.

### Minimal reproduction
```latex
\documentclass{article}
\usepackage{colortbl}  % comment this line out to show difference

\begin{document}

\begin{tabular}{|l|c|}
  one&two\\
  three&four
\end{tabular}

$
\begin{array}{ccc}
  ~1~&~2~&~3~&~4~&~5~&~6~&~7~&~8~&~9
\end{array}
$

\end{document}
```
Without importing `colortbl`:
<img width="641" alt="image" src="https://github.com/davidcarlisle/dpctex/assets/61113575/ffabc7dd-4c9f-4ede-a578-1fdae772c83d">
Importing `colortbl` using `\usepackage{colortbl}`:
<img width="627" alt="image" src="https://github.com/davidcarlisle/dpctex/assets/61113575/8e6b9284-4771-4f0a-8b60-7b36a24e8170">

The difference is easier to see when superimposing both PDFs (red is without importing, blue is with `\usepackage{colortbl}`:
<img width="638" alt="image" src="https://github.com/davidcarlisle/dpctex/assets/61113575/79372623-1069-440f-8881-45f4bef82a7a">

### Files for reproduction
[no_import.log](https://github.com/davidcarlisle/dpctex/files/14769677/no_import.log)
[no_import.pdf](https://github.com/davidcarlisle/dpctex/files/14769679/no_import.pdf)
[with_import.log](https://github.com/davidcarlisle/dpctex/files/14769683/with_import.log)
[with_import.pdf](https://github.com/davidcarlisle/dpctex/files/14769684/with_import.pdf)

**Comment by davidcarlisle** [comment]
The posted code produces 

```
! Extra alignment tab has been changed to \cr.
```

which does not show in your log, is the log from the code shown?

**Comment by davidcarlisle** [comment]
The spacing differences  if I change teh second preamble to `cccccccccc` ae due to `array` package.##this has a documented changee on spacing of vertical rules. In teh original `tabular` a vertical rule does not increase teh table width, negative space is added to compensate.  With `array` a vertical rule does add its width.

So some difference are expected in teh first tabular. the second one with no `|` the difference is less expected, I will trace later, unless @FrankMittelbach looks first.

```
\documentclass{article}
%\usepackage{array}
\begin{document}

\begin{tabular}{|l|c|}
  one&two\\
  three&four
\end{tabular}

$
\begin{array}{cccccccccc}
  ~1~&~2~&~3~&~4~&~5~&~6~&~7~&~8~&~9
\end{array}
$

\end{document}
```

**Comment by FrankMittelbach** [comment]
Isn't the second caused by `~` no longer producing \nobreakspace + an empty ord atom (which it shouldn't have) so that now a space at the end a cell gets dropped and hasn't been dropped in the past (as it should have).  `~` is not supposed to be a space that is never dropped, it is supposed to be like `\ ` but without allowing for a line break *before* the space which makes it equivalent to `\ ` in situations where linebreaks do not happen.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  yes (thanks for looking I couldn't look earlier)  but the distinction is not "in the past/now" but "no-array package/array package" so probably we should document difference  (or arguably make the kernel tabular treat spaces the same way as array?

**Comment by FrankMittelbach** [comment]
You are saying that `~` is different depending on array or not array package? That would be odd, yes.

**Comment by FrankMittelbach** [comment]
that's odd and I guess my explanation can't be right.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  with `array` there's always an unskip at the end of the cell

with the kernel tabular only `\@tabclassz` does the unskip `\@arrayclassz` leaves the skip in place, normally white space in math is ignored anyway so it makes no difference but with an explicit space it does.

**Comment by FrankMittelbach** [comment]
well, yes, perhaps we should revert to that in array rather than explaining the difference. It does make kind of sense that explicit spaces in a math cell survive. Can't be done the same way as in the core though because basically any column in a tabular could hold math cells not just a complete array environment and it would be really odd if a `>$c<$` column would behave differently from a full array env.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  `\ifhmode\unskip\fi` ?

**Comment by FrankMittelbach** [comment]
sort of, but as the preamble is build with `\xdef` that's not quite getting you there. Maybe
```
\protected\def\textonly@unskip{\ifhmode\unskip\fi}
```

**Comment by muzimuzhi** [comment]
I did some testing by applying @FrankMittelbach's idea of `\textonly@unskip` to `\insert@column`. It fixed the issue here, and passed the test suite in [`required/tools` directory in `latex3/latex2e` repo](https://github.com/latex3/latex2e/tree/1ce0cd8983b72909fc7f2645ea3d6400c0be98ae/required/tools).

```tex
\documentclass{article}

\newcommand{\test}{%
  \par\noindent
  \parbox{3cm}{%
    Both sides\\
    $\begin{array}{|c|c|c|}
      ~1~&~2~&~3~
    \end{array}$}
  \parbox{2.8cm}{%
    Left side only\\
    $\begin{array}{|c|c|c|}
      ~1 &~2 &~3
    \end{array}$}
  \parbox{2.8cm}{%
    Right side only\\
    $\begin{array}{|c|c|c|}
      1~& 2~& 3~
    \end{array}$}
  \parbox{2.8cm}{%
    None\\
    $\begin{array}{|c|c|c|}
      1 & 2 & 3
    \end{array}$}
}

% save output of \test without "array"
\setbox0=\hbox{\parbox{\linewidth}{\test}}

\usepackage{array}

\begin{document}

\subsection*{Without array}
\noindent
\usebox0

\subsection*{With array, before}
\test

\subsection*{With array, after}
\makeatletter
\ifdefined\UseTaggingSocket
  % if compiled using pdflatex-dev or the like
  \def\insert@column{%
     \UseTaggingSocket{tbl/cell/begin}%
     \the@toks \the \@tempcnta
     \ignorespaces \@sharp \textonly@unskip
     \the@toks \the \count@ \relax
     \UseTaggingSocket{tbl/cell/end}%
  }
  \def\insert@pcolumn{%
     \UseTaggingSocket{tbl/pcell/begin}%
     \the@toks \the \@tempcnta
     \ignorespaces \@sharp \textonly@unskip
     \the@toks \the \count@ \relax
     \UseTaggingSocket{tbl/pcell/end}%
  }
\else
  \def\insert@column{%
     \the@toks \the \@tempcnta
     \ignorespaces \@sharp \textonly@unskip
     \the@toks \the \count@ \relax}
\fi

\protected\def\textonly@unskip{\ifhmode\unskip\fi}
\makeatother

\test
\end{document}
```

![image](https://github.com/davidcarlisle/dpctex/assets/6376638/5911e3bf-81bd-45ae-987f-172e9c29dfba)

**Comment by FrankMittelbach** [comment]
@davidcarlisle is it possible to transfer this issue to latex2e or do we need to open a new one for tools?

**Comment by davidcarlisle** [comment]
@FrankMittelbach  can only move within an organization so simplest to open a new one on tools.array I think then close here.

**Comment by davidcarlisle** [comment]
@jovyntls thanks for your report. As you will see from the above comment Frank has opened the issue at the main LaTeX2e repositiory, for the array package where this difference originates. I'll close here.
