### ISSUE TITLE
autopict.sty is (functionally) empty - broken asymptote/tex

### ISSUE THREAD

**Issue by norbusan** [davidcarlisle/dpctex#7]
Hi David,

with the update in 16 Aug 2017, svn 41881, the file autopict.sty in texlive is now completely empty, which seems to break asymptote when using the plain tex backend, which relies on graphics-pln.

I tried the .ins file to generate the file, but I got the same empty file (only comments and endinput).

All the best

Norbert

**Comment by davidcarlisle** [comment]
On 16 January 2018 at 14:48, Norbert Preining <notifications@github.com>
wrote:

> Hi David,
>
> with the update in 16 Aug 2017, svn 41881, the file autopict.sty in
> texlive is now completely empty, which seems to break asymptote when using
> the plain tex backend, which relies on graphics-pln.
>
> I tried the .ins file to generate the file, but I got the same empty file
> (only comments and endinput).
>
> All the best
>
> ooh it's been broken for a while then.

autopict.sty was designed to offload parts of the latex kernel so you had a
bit more space in emtex on a 500K PC...
the docstrip guards were complicating things and we cleaned up in the
latexbase and removed the guards for generating the "autoload" version of
the format...

I guess that the simplest thing would be to resurrect an old copy of
autopict.sty and just put a frozen copy into  graphics-pln rather than
expecting a .ins file to generate one?

David

**Comment by norbusan** [comment]
Since it seems to be necessary to for asymptote with (plain) tex, I would say having the frozen copy is fine. Do you want me to send it to you?

**Comment by davidcarlisle** [comment]
no I can make one thanks

**Comment by davidcarlisle** [comment]
update gone to ctan, thanks for raising the issue.

**Comment by norbusan** [comment]
Thanks for the quick fix!
